### ISSUE TITLE
Tab suggestion

### ISSUE THREAD

**Issue by Radiation-pi** [Nolezor/BetterViewDistance-Paper#2]
I want this plugin for a long time, thanks for coding it! I hava 2 suggestions:
1. It's a good idea to use the tab completion to save time and make sure I type the right player name.
2. Add a perm such as betterviewdistance.viewrange.<amount> or save player's viewdistance in the sql or yml to keep their viewdistance before relog.
I am not a native English user and I'm sorry if you can't understand me.

**Comment by Nolezor** [comment]
Hi Radiation-pi,
First of all, thanks for the positive review, it's always pleasing seeing your work being recognized.
About the suggestion, those are all good ideas but I'm working on another project right now, I'll still make sure to implement both a database and the tab completion for the next version.

**Comment by Radiation-pi** [comment]
Thanks for your reply! I will waiting for you! Don't be so care about it and do what you want to do first.

**Comment by Nolezor** [comment]
Hi Radiyion-pi,
It took me a bit more than expected to find time for this, I've finished implementing the tab completion and the storage part is almost done, if everything works I might be able to update both the repo and the jar in a day or two.
